Добавил свойство курсора pointer при наведении на "Обсуждение"
intocode/iqa-frontend pull request #334
Opened 2023-02-23 20:59 UTC by brz95

fixes #308

2023-02-23 21:03 UTC, kuduzow commented
Это не решает проблему, курсор все еще стандартный. Ты его для svg добавил

2023-02-23 22:08 UTC, kuduzow requested changes

2023-02-24 04:43 UTC, kuduzow requested changes

2023-02-24 04:43 UTC, kuduzow commented on src/features/questions/questions-list/QuestionBlock.jsx
> +    cursor: pointer;
Это должно быть в компоненте ниже, там где непосредственно есть эта кнопка

2023-02-24 04:47 UTC, brz95 commented on src/features/questions/questions-list/QuestionBlock.jsx
> +    cursor: pointer;
У меня такое ощущение что если я его отпущу на компонент ниже то будет 3 измененных файла, а не в один как сейчас

2023-02-24 04:58 UTC, kuduzow approved these changes

2023-02-24 04:59 UTC, merged